### ISSUE TITLE
Not an issue - a question for Quick access Button mailfence.com

### ISSUE THREAD

**Issue by David73230** [tdmrhn/Thunderbird-Quick-Access-Buttons#11]
Hei i tryed to send you an email, but  it seems my email provider don't allow to send emails to you.
For that reason i ask you if you can develop a Quick Access Button for mailfence.com, i installed it for
Tuta Mail, and it works great. Thank you so much.
Best regards
David

**Comment by tdmrhn** [comment]
Sure here it is;
https://addons.thunderbird.net/en-GB/thunderbird/addon/mailfence-quick-access/

**Comment by David73230** [comment]
Super, thank you!
