### ISSUE TITLE
Microsoft Teams: Browser version unsupported

### ISSUE THREAD

**Issue by pols12** [tdmrhn/Thunderbird-Quick-Access-Buttons#14]
Dear maintainer,

The Microsoft Teams access does not work, `https://teams.microsoft.com/v2/unsupported-browser#isLinux=true&env=work` URL gives an error message: Your browser version is not supported.

The user-agent should probably be overridden.

Regards,

**Comment by tdmrhn** [comment]
Hi @pols12 
Thanks for the heads up, you can try with 0.2 - added browser version check bypass
