### ISSUE TITLE
Calendar is messed up TB 128+

### ISSUE THREAD

**Issue by PegHorse** [tdmrhn/Thunderbird-Quick-Access-Buttons#15]
![image](https://github.com/user-attachments/assets/c1f843c0-7710-4199-8faf-65310144d6ac)
No needs to say more, the picture show the mess itself.

**Comment by tdmrhn** [comment]
Hi @PegHorse i couldn't replicate what you have.
![image](https://github.com/user-attachments/assets/50d25897-a162-4e21-84c0-62157b1f9a8a)

* Also this is just a tool with 3 lines of code that opens the calendar url, the page render is handled by thunderbird built-in browser.
https://github.com/tdmrhn/Thunderbird-Quick-Access-Buttons/blob/main/Google%20Calendar/redirect.js

**Comment by tdmrhn** [comment]
Seems it is fine now.

**Comment by PegHorse** [comment]
I finally found out the cause of the issue, it's a bad behavior from the Extension "Dark Reader".
The author never replied to me but, i finally found out the font was customized, so i disabled it and it works again.
