### ISSUE TITLE
Unsupported browser error on login (Slack) (Thunderbird 115.9.0 - Linux)

### ISSUE THREAD

**Issue by owenwastaken** [tdmrhn/Thunderbird-Quick-Access-Buttons#3]
The Slack - Quick Access extension (Version 0.2) displays the following error on the slack sign-up screen after inputting workspace URL and email address:

We're very sorry, but your browser is not supported!

**Comment by tdmrhn** [comment]
@owenwastaken  thanks for the feedback.
Version 0.2 already has replacement code that shows the Thunderbird browser as Firefox 122. The Slack quick access tab is one of my default tabs that I use daily, and so far this trick has worked for me. It may be necessary to have Firefox installed, which I haven't tried but I can think of.

**Comment by fpusan** [comment]
Happens to me too with Version 0.2 of this package, Thunderbird 115.10.1 and Firefox 125.0.3,  running on Ubuntu 22.04.6

**Comment by tdmrhn** [comment]
It seems the confirmation code screen is currently not working on app subdomain, i improved the code and accept all subdomains, try version 0.3

**Comment by owenwastaken** [comment]
The updated version fixes the issue. Thanks!

**Comment by neurodiverseEsoteric** [comment]
This issue has returned
